#!/usr/bin/python3

import numpy
import math
import matplotlib.pyplot as plt

import sys
sys.path.append('..')
from non_lin_osc import *

# example of pseudoplastic oscillator

w0 = 1
tau = 0.5
vc = 1
k = 0.5
FF = numpy.array([0.5,1,2,3,4])
ww = numpy.linspace(0.1,2,100)


amp = numpy.zeros(ww.size)
ph  = numpy.zeros(ww.size)

for F in FF:

  for i in range(ww.size):
    w = ww[i]
    uv = osc_solve_vdp(osc_pseudopl1, [w0,tau,vc,k], F,w)

    amp[i] = numpy.hypot(uv[0],uv[1])/F
    ph[i]  = numpy.arctan2(uv[1],uv[0])

  plt.plot(ww, amp, label=F)

plt.xlabel('frequency')
plt.ylabel('amplitude/drive')
plt.legend()
plt.savefig('plot_pseudopl.png')
