#!/usr/bin/python3

import numpy
import matplotlib.pyplot as plt
import fit_res_df0v0 as fit_res
import f4wire001 as f4wire

t1='2023-02-09 14:46'
t2='2023-02-09 16:44'
#t2='2023-02-09 17:35' # non-linear
name="w1bt"
#wire = f4wire.wire_info_t(name)

# Get all sweeps
sweeps = f4wire.get_sweep_range(name, t1, t2, cache="test_cache/fit_res002_bphase.cache")

# fit all data
data = numpy.row_stack(sweeps)
fit = fit_res.fit(data, npars=7, do_fit=1)

# plot data
(fig, ax) = plt.subplots(1,2)
n=0
for s in sweeps:
  n+=1
  drive = numpy.mean(s[:,4])
  fit_res.plot(ax[0], ax[1], s, fit, sc=1/drive, sh=5*n, npts=200)


ax[0].set_ylabel('Vx/I [V/A]')
ax[1].set_ylabel('Vy/I [V/A]')
plt.gcf().set_size_inches(12, 6)
plt.savefig("fit_res_df0v0.png", dpi=100)
